
# Configuration de la source de donnees (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/ChapChap?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

# Dossier d'upload et taille de fichiers
app.upload.dir=/opt/chapchap/uploads/preuves/
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

# Thymeleaf
spring.thymeleaf.cache=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Minimise les infos Spring Boot
spring.main.log-startup-info=false
spring.main.banner-mode=off

server.servlet.session.persistent=false
