spring.application.name=chapchap
spring.profiles.active=dev
# =======================
# DEV - LOCAL
# =======================
server.port=9000

# =======================
# GROQ AI
# Console: https://console.groq.com
# =======================
groq.api.url=https://api.groq.com
groq.api.key=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






